language: java

before_script: 
  - cd $TRAVIS_BUILD_DIR
  - echo "<settings><profiles><profile><id>default</id><activation><activeByDefault>true</activeByDefault></activation>
              <properties>
              <nldi.url>jdbc:postgresql://127.0.0.1:5432/nldi</nldi.url>
              <nldi_user.username>nldi_user</nldi_user.username><nldi_user.password></nldi_user.password>
              <dbunit.username>nldi</dbunit.username><dbunit.password></dbunit.password>
              </properties></profile></profiles></settings>"
        > ~/settings.xml

script:
  - mvn verify --settings ~/settings.xml