
mybatis:
  type-aliases-package: gov.usgs.wma.mlrlegacy
  configuration:
    cache-enabled: false
    lazy-loading-enabled: false
    aggressive-lazy-loading: false
  mapper-locations: "classpath:monitoringLocation.xml"

spring:
  datasource:
    url: "jdbc:postgresql://${mlrLegacyDbHost}:${mlrLegacyDbPort}/mlr_legacy"
    username: ${mlrLegacyDataUsername}
    password: ${mlrLegacyDataPasswd}
    driver-class-name: org.postgresql.Driver
