
mybatis:
  type-aliases-package: gov.usgs.wma.mlrlegacy
  configuration:
    cache-enabled: false
    lazy-loading-enabled: false
    aggressive-lazy-loading: false
  mapper-locations: "classpath:mybatis-config.xml"

spring:
  datasource:
    url: ${mlrLegacyDbUrl}
    username: ${mlrLegacyUsername}
    password: ${mlrLegacyPasswd}
    driver-class-name: org.postgresql.Driver
